### ISSUE TITLE
deklaracja zmiennych jako LIGHT a nie SWITCH

### ISSUE THREAD

**Issue by pepsonEL** [lkankowski/arduino-multi-relay2#17]
Witam
Mam pytanko.... bo korzystam z Twojego sketcha v2 i działa on super , zarówno jako właczniki jak i sensory(kontaktrony). Korzystam z niego w połączeniu z HomeAssistant. Jedyne co mnie wkurza i pytanie czy dałoby się to zmienić.... a mianowicie to w Home Assistant encje od włączników są wykrywane jako encja switch.xxxxxxx Czy da się zmienić coś w sketchu aby można było wybierać ajk encja ma być wykrywana czy jako light.xxxxxxx czy jako switch.xxxxxxx ? To byłoby super rozwiązanie bo wtedy dla świateł użytkownicy deklarowaliby sobie że ma być to jako light i było by to zgodne z założeniami automatyki i użytkownia w Home Assistant , a gdyby chcieli aby inne wyjścia były wykrywane jako switch bo np mają w tym sketchu też sterowanie gniazdami to wtedy by wybierali sobie jako switch. Jeśli to możliwe proszę pomyśl nad tym bo byłoby to super uniwersalne rozwiązanie i dobre dla zgodności z innymi systemami.....

**Comment by lkankowski** [comment]
Cześć,
Dzięki za miłe słowa.
Wg specyfikacji MySensors dla wszelkich urządzeń ze stanami WŁ/WYŁ stosuje
się typ S_BINARY, więc nie ma możliwości rozróżniania. Spróbuj popytać na
mysensors.org - może oni coś doradzą.


pt., 27 sie 2021, 09:55 użytkownik pepsonEL ***@***.***>
napisał:

**Comment by pepsonEL** [comment]
OK dzięki :) Byłoby fajnie gdyby dało się.... Daj znać jak coś się dowiesz....
A BTW czy działasz coś dalej z tym sketchem ? Rozwijasz go i coś zmieniasz ? Planujesz jakieś zmiany ? I też fajnie jakby udało się rozwiązać ten problem z właczaniem lub wyłaczaniem grupowym właczników co też jest zgłoszone w issue 13.

**Comment by pepsonEL** [comment]
Może to coś też podpowie....
https://www.home-assistant.io/integrations/light.mysensors/

**Comment by lkankowski** [comment]
Czyli działa zgodnie z dokumentacją :)

**Comment by pepsonEL** [comment]
Czyli nie da sie zrobić aby były jako LIGHT ?

**Comment by lkankowski** [comment]
Specyfikacji MySensors nie przeskoczę.

**Comment by pepsonEL** [comment]
OK dzięki. A powiedź mi korzystasz z Home Assistanta już ? Bo zastanawiam sie nad przejściem z MySensors na coś bardzoiej co jest aktualizowane.... Myśle trochę o ESPHome... Bo MySensors chyba umarło.... nic nie pojawia się nowego chyba już dwa lata.... A to już kiepsko wróży.... A podobno ESPHome jest pod wachlarzem HomeAssistant

**Comment by lkankowski** [comment]
Nie używam HA - próbowałem, ale nie przypadł mi do gustu.
