### ISSUE TITLE
RELAY_IMPULSE_INTERVAL is only 255 (char)

### ISSUE THREAD

**Issue by cyniu88** [lkankowski/arduino-multi-relay2#18]
Hi,

how to increase the value of RELAY_IMPULSE_INTERVAL, currently it can be set as char (255 ms),

If I change relayOptions from uint8_t to uint16_t the RII can be set to 1500ms, for example, but the relay does not work properly

**Comment by lkankowski** [comment]
You have to change the:
`const unsigned long RELAY_IMPULSE_INTERVAL = 250;`
In config.h.


niedz., 29 sie 2021, 14:54 użytkownik cyniu88 ***@***.***>
napisał:

**Comment by cyniu88** [comment]
yep, i know that, but unfortunately these macros are cast to char so it doesn't get above 255. 255 ms for doorbell is not enough

**Comment by lkankowski** [comment]
This is not a macro. Try use "1500UL" instead.

pon., 30 sie 2021, 21:26 użytkownik cyniu88 ***@***.***>
napisał:

**Comment by lkankowski** [comment]
I assume, that it works correctly.
