### ISSUE TITLE
Błędy przy kompilacji 2.3.0

### ISSUE THREAD

**Issue by pepsonEL** [lkankowski/arduino-multi-relay2#19]
Spróbowałem wgrać sketch i mam nie wiem errory
https://pastebin.com/7RM6ePRe
a to config:
https://pastebin.com/y6Mn3i0u

**Comment by pepsonEL** [comment]
0;255;1;0;47;toogle debug stats

**Comment by pepsonEL** [comment]
Zmieniłem komunikację na 9600 ale niestety tak samo nie działa gaszenie np całego oświetlenia.... Nieraz złapie 3/4 świateł nieraz mniej różnie.

**Comment by lkankowski** [comment]
No to teraz zostaw prędkość 9600 i dodaj zwiększenie bufora na komunikację za pomocą flag kompilacji `SERIAL_RX_BUFFER_SIZE`, np. tak:
```
build_flags =
  ;  --verbose
  -D SKETCH_VERSION="2.3"
  -D CONFIG_VERSION=20 ;; change to force reset relay state to OFF in eeprom on first start
  -D DEBUG_STATS=1000
  ; -D DEBUG_COMMUNICATION
  ; -D DEBUG_ACTION
  ; -D DEBUG_STARTUP
  ; -D IGNORE_BUTTONS_START_MS=2000
  ; -D EXPANDER_PCF8574
  -D EXPANDER_MCP23017
  -D SERIAL_RX_BUFFER_SIZE=256
```
Oczywiście ustaw też inne flagi, których używasz.

Co do diagnostyki wydajności, to wkleiłeś potwierdzenie wykonania komendy, a po chwili powinna się wyświetlić informacja w stylu:
```
# 1000 loop stats for 31 buttons: (end-start)=649ms, cumulative_loop_millis=636ms
```

**Comment by pepsonEL** [comment]
`0;255;1;0;24;1
0;255;1;0;47;toogle debug stats
# 1000 loop stats for 57 buttons: (end-start)=13895ms, cumulative_loop_millis=13890ms`

**Comment by pepsonEL** [comment]
Dałem jeszcze na test 
`  -D SERIAL_RX_BUFFER_SIZE=1024
  -D SERIAL_TX_BUFFER_SIZE=1024`
I chyba jest lepiej. Jak daje gaszenie wszystkich świateł to gasi. Jeszcze będę testować.
Ale już z zapalaniem jest gorzej.... nie zapala wszystkich a jak zapala to dziwnie światła mrugają... Coś mam wrażenie że brakuje prądu do sterowania w Arduino, ale to też dziwne bo jak zapalam wszystkie światła ale powoli czyli pokojami to zapalają się i palą ok. Ale jak daje polecenie zapalenia wszystkich na raz to część świateł jakoś mruga albo nie zapalą się....
Ale grunt że działa gaszenie wszystkich.....

**Comment by lkankowski** [comment]
Wg mnie to potwierdza, że problemem nie jest mój kod :)
Co do prądu, to fajnie jakbyś zrobił dokładne pomiary. Jeżeli masz przekaźniki elektromagnetyczne, to z tego co kojarzę, mogą przy rozruchu brać większy prąd.

Ciekawostka odnośnie wydajności - test bada czas w jakim wykonane zostało 1000 razy sprawdzenie wszystkich przełączników - krótko mówiąc, 1000-krotne wywołanie pętli loop().
U mnie jest niecałe 650ms przy 31 przełącznikach, czyli jedna pętla zajmuje 0,65ms.
U Ciebie jest 13900ms (13,9s) przy 57 przełącznikach, czyli jedno sprawdzenie wszystkich zajmuje 13,9ms - ponad 20x dłużej niż u mnie. Korygując o ilość (57 vs 31) to w dalszym ciągu ok. 12x dłużej. To jest efekt zastosowania expanderów.
Z drugiej strony nie jest tak źle jak myślałem, bo spodziewałem się, że jest gorzej :)
13,9ms to znacznie mniej niż de-bouncing (50ms) i mniej niż standardowy odstęp przy double-click (350-400ms).
