### ISSUE TITLE
Problem z konfiguracją jako IMPULS

### ISSUE THREAD

**Issue by pepsonEL** [lkankowski/arduino-multi-relay2#20]
Witam
Jest problem.... W nowej wersji nie działa przekaźnik poprawnie gdy jest skonfigurowany jako IMPULS.

  {24, 29, RELAY_TRIGGER_HIGH | RELAY_IMPULSE, -1, "Brama garażowa"},  // WŁ: wej do garażu
  {25, 30, RELAY_TRIGGER_HIGH | RELAY_IMPULSE, -1, "Brama wjazdowa"},  // WŁ: wej do garażu
  
  Powinien się wyłączyć automatycznie a on jest cały czas załaczony.... Na 100% w wersji 2.2.1 było ok a tu dzis zobaczyłem że nie wyłącza się.... Cały czas jest zwarty.....

**Comment by lkankowski** [comment]
Dziwne - wgrałem Twój konfig i u mnie działa:
```
19:54:04.212 > 0;255;3;0;14;Gateway startup complete.
19:54:04.216 > 0;255;0;0;17;2.3.2
19:54:04.216 > 0;255;3;0;11;Multi Relay
19:54:04.218 > 0;255;3;0;12;2.3
...
19:54:04.284 > 0;24;0;0;3;Brama garażowa
19:54:04.287 > 0;25;0;0;3;Brama wjazdowa
...
...
19:54:04.401 > 0;24;1;0;2;0
19:54:04.405 > 0;25;1;0;2;0
...

0;24;1;0;2;1                                      --> ręcznie wysłane polecenie załączenia
19:54:14.371 > 0;24;1;0;2;1             --> potwierdzenie ze sketcha
19:54:14.625 > 0;24;1;0;2;0             --> automatyczne wyłączenie po ok. 250ms


0;25;1;0;2;1                                     --> analogicznie jak wyżej
19:54:44.645 > 0;25;1;0;2;1
19:54:44.898 > 0;25;1;0;2;0
```

**Comment by pepsonEL** [comment]
Faktycznie działa.... to coś chyba HA miesza.... Bo przekaźnik się wyłącza a w HA mam jakby był włączony.... Muszę sprawdzić to....

**Comment by lkankowski** [comment]
No to zamykam :)

**Comment by pepsonEL** [comment]
Wiesz co dziwnie to wygląda bo na dwóch przekaźnikach z tym impuls pierwsze kliknięcie działa ok i przekaźnik włacza się na moment i wyłącza, ale już kolejne kliknięcie powoduje że w HA widnieje cały czas jakby był włączony i stan ma ON natomiast fizycznie jest wyłączony czyli też poprawnie się właczył na moment i wyłączył. Muszę kolejny raz kliknąć w HA aby jego stan zmienił się na OFF. Dziwne to. Na wersji 2.2.1 działało to napewno ok bo tych przekaźnikow chyba 56 i 55 używam do uchylania bram i używałem tego już długo....

**Comment by lkankowski** [comment]
Tylko upewnij się, że zmiany buforów transmisji szeregowej tego nie powodują - jeżeli ustawiłeś łącznie 2048 bajty, to zużyłeś tylko na to 1/4 pamięci Arduino Mega.

**Comment by pepsonEL** [comment]
Ustawiłem tylko dla RX 1024. Dla TX nie ustawiałem....

śr., 3 lis 2021, 23:07 użytkownik lkankowski ***@***.***>
napisał:

**Comment by pepsonEL** [comment]
Coś jest jednak nie tak.... Wyłaczyłem całkowicie ten parametr i jest tak że ok impuls idzie na przekaźnik i włacza się on tylko na mniej niż 1 sekunda ale w Home Assistant switch od tego pozostaje włączony. A powinien automatycznie wrócić do stanu OFF i tak było wcześniej....

**Comment by lkankowski** [comment]
W takim razie wklej loga z komunikacji po serial porcie - tam będzie widać czy problem tkwi w wysyłaniu stanu, czy może po stronie HA.
Dodam, że ten przypadek jest dość dokładnie pokryty w unit testach i testy przechodzą prawidłowo (https://github.com/lkankowski/arduino-multi-relay2/blob/master/test/test_desktop/test_main.cpp#L263). Chociaż muszę przyznać, że sama komunikacja nie jest tu sprawdzana.

**Comment by pepsonEL** [comment]
A w jaki sposób dać logi po serialu z wywołaniem tego polecenia jakby kliknięcia?

**Comment by lkankowski** [comment]
Podłącz się serial monitorem i uruchom przekaźnik odpowiednim przyciskiem.
Potem do porównania zrób to samo po połączeniu z HA i do porównania wrzuć kawałek loga HA.

**Comment by pepsonEL** [comment]
Bo problem jest jak przyciskiem z HA to uruchamiam....

pon., 8 lis 2021, 14:32 użytkownik lkankowski ***@***.***>
napisał:

**Comment by pepsonEL** [comment]
Logi z seriala. ID 56 to przekaźnik natomiast ID26 to kontaktron na bramie.
```
0;56;1;0;2;1
0;56;1;0;2;1
0;56;1;0;2;0
0;26;1;0;16;1
0;56;1;0;2;1
0;56;1;0;2;1
0;56;1;0;2;0
0;26;1;0;16;0
```

**Comment by pepsonEL** [comment]
Aktualny config
https://pastebin.com/48ewSfTq

Kontaktron jest zwarty jak brama jest zamknięta. A powiązanie mam tylko w HA zrobiony przycisk wirtyualny że używa stanu z kontaktronu a wyzwalanie impulsu używa przekaźnika z Twojego sketcha.  Oczywiście kontatron też jest przez Twój sketch zrobiony....

Do otwierania bramy jest jeden przekaźnik i fizyczny klawisz. Natomiast do uchylania drugi przekaźnik ale bez klawisza i tylko z HA nim steruję. 
A osobno do bramy jest fabryczny pilot Hormanna.

**Comment by lkankowski** [comment]
No i się okazało, że był bug :)
Na masterze masz poprawkę.
Tak naprawdę bug był od momentu wprowadzenia typu V_TRIPPED dla kontaktronów, ale obsługa była w innej kolejności i błąd na Twojej konfiguracji się nie ujawniał.

**Comment by pepsonEL** [comment]
Ok przetestuje....

śr., 10 lis 2021, 10:50 użytkownik lkankowski ***@***.***>
napisał:

**Comment by pepsonEL** [comment]
I po raz kolejny BINGO. Działa jak należy :) Możesz scalić i wydać w ostatecznym release.... może zrobić 2.3.2 :) Dzięki raz jeszcze za super jak zawsze pomoc.
