### ISSUE TITLE
Add ESP32 Support

### ISSUE THREAD

**Issue by lkankowski** [lkankowski/arduino-multi-relay2#22]

**Comment by pepsonEL** [comment]
Na jakiej zasadzie chcesz wprowadzić obsługę ESP32 ? Zamiast Arduino ?

**Comment by lkankowski** [comment]
Tak samo jak z ESP8266 - po prostu kwestia dodania konfiguracji kompilacji, bo MySensors ma już obsługę. No i pewnie kilka drobnych zmian, żeby się kompilowało.

**Comment by pepsonEL** [comment]
Czyli ESP w połączeniu z Arduino tak ?

**Comment by lkankowski** [comment]
Nie - w całości na ESP. Nazwa Arduino odnosi się nie tylko do płytek, ale też do frameworka. ESP także można programować we frameworku Arduino :)

**Comment by pepsonEL** [comment]
Czyli że soft wgrywamy na ESP32 i do niego np trzeba podłaczyć ekspandery aby obsługiwać jak do tej pory przekaźniki i przełaczniki ścienne ? Bo teraz część podłaczeń szło na arduino mega a reszta jak coś przez ekspandery....

**Comment by chytreg** [comment]
> ESP32 - Experimental! Tests with LAN worked fine, but had no luck with MQTT

Maybe you have the hardware, not a software problem, did you try to run on Olimex or a self-made RJ45 connection?

from: https://esphome.io/components/ethernet.html, 

> If your ethernet board is not designed with an ESP32 built in, chances are that you are going to use flying leads, dupont wires, etc. to connect the ethernet to the ESP32. This is probably to fail as the ethernet interface uses a high frequency clock signal. For more information and wiring details refer to the the link in the See also section.

And from see also section: https://pcbartists.com/design/embedded/esp32-ethernet-phy-schematic-design/

**Comment by lkankowski** [comment]
> Maybe you have the hardware, not a software problem, did you try to run on Olimex or a self-made RJ45 connection?

I didn't try RJ45 - just on WiFi.
And yes - I could have some hardware problems, because only ESP32 I have is very strange (http://esp32.net/images/eBox/ESP32-Bit/). It has very poor wifi signal, even with external antenna.
