### ISSUE TITLE
Automatyczne losowe wyzwalanie przełączników

### ISSUE THREAD

**Issue by pepsonEL** [lkankowski/arduino-multi-relay2#3]
Zakładam nowe issue w związku z automatycznym załączaniem przekaźników. Wrzucam link z logów z poprzedniego issue #1 https://github.com/lkankowski/arduino-multi-relay2/issues/1 aby była kontynuacja:
https://pastebin.com/npvT5haQ

Wgram dziś ponownie nową wersję ale nie wiem dlaczego są wyzwalane te przekaźniki skoro nikt ich fizycznie nie klika nie uruchamia. A tym bardziej wracając na wersję programu 1.2 wszystko jest ok i problemów nie ma. To jest najbardziej zastanawiające.

**Comment by lkankowski** [comment]
Wyzwalane są przełączniki, a nie przekaźniki.
Spróbuj na początku funkcji "before()" dać np. "delay(2000);" i zobacz czy masz ten sam efekt.
Jakiego rodzaju masz przełączniki? Mechaniczne czy jakieś zasilane, np. dotykowe? Jak masz je podłączone, jakie kable, jak długie...

**Comment by pepsonEL** [comment]
Przełaczniki mam zwykłe mechaniczne mono-stabilne LEGRAND NILOE. Mam do nich podłaczoną skrętkę - jedna para(jena żyła GND druga żyła SYGNAŁ-Arduino MEGA).
Długości hmmmm szczerze ciężko powiedzieć.... ale niektóre nawet są krótsze niż 10m (dwa z tych co wariują napewno)


W pliku main.cpp mam dodać aby tak to wyglądało? :

// MySensors - This will execute before MySensors starts up
void before() {
  Serial.begin(115200);
delay(2000);
  #ifdef DEBUG_STARTUP
    Serial.println(String("# ")+(debugCounter++)+" Debug startup - common config: MONO_STABLE_TRIGGER="+MONO_STABLE_TRIGGER
                   +", RELAY_IMPULSE_INTERVAL="+RELAY_IMPULSE_INTERVAL+", BUTTON_DEBOUNCE_INTERVAL="+BUTTON_DEBOUNCE_INTERVAL
                   +", BUTTON_DOUBLE_CLICK_INTERVAL="+BUTTON_DOUBLE_CLICK_INTERVAL+", BUTTON_LONG_PRESS_INTERVAL="+BUTTON_LONG_PRESS_INTERVAL);

    #ifdef USE_EXPANDER
      Serial.println(String("# ")+(debugCounter++)+" Debug startup - expander config");
      for(int i = 0; i < gNumberOfExpanders; i++) {
        Serial.print(expanderAddresses[i]);
        Serial.print(",");
      }
      Serial.println();
    #endif

**Comment by lkankowski** [comment]
Dobre miejsce na "delay" - sprawdz.

**Comment by pepsonEL** [comment]
Ok postaram się dziś sprawdzić.

**Comment by lkankowski** [comment]
No to niezła zagwostka. Poprawiłem sprawdzanie pinów przycisków podczas startu - poprzednio brakowało INPUT_PULLUP.
Podczas startu możesz poobserwować stan EEPROM w liniach:
```
# 57 Debug startup - EEPROM (relay state starts at 1)
# 58 22,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,
```
Pierwsza wartość to wersja (w tym wypadku "22"), kolejne to stan poszczególnych przekaźników.

Następnie obserwuj linie ze stanem pinów przycisków:
```
# 59 Debug startup - buttons pin state
# 60 1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,
```
Tu prawdopodobnie wartości były lipne z powodu braku INPUT_PULLUP.

No i to jest u Ciebie ciekawe - przyciski się wyzwalają zaraz po starcie:
```
Ośw. schowek - Click for relay 23
# 88:2671 Relay::changeState: old_state=1, new_state=0, _hasStartupOverride=0, _eepromIndex=23, (uint8_t) state=0, _isImpulse=0
0;23;1;0;2;0
Ośw. garaż-1 sekcja - Click for relay 7
# 89:2684 Relay::changeState: old_state=1, new_state=0, _hasStartupOverride=0, _eepromIndex=7, (uint8_t) state=0, _isImpulse=0
0;7;1;0;2;0
Ośw. zew. od kotłowni - Click for relay 10
# 90:2701 Relay::changeState: old_state=1, new_state=0, _hasStartupOverride=0, _eepromIndex=10, (uint8_t) state=0, _isImpulse=0
0;10;1;0;2;0
Ośw. kotłownia - Click for relay 6
# 91:3022 Relay::changeState: old_state=1, new_state=0, _hasStartupOverride=0, _eepromIndex=6, (uint8_t) state=0, _isImpulse=0
0;6;1;0;2;0
```
Są tu 4 akcje wywołane pomiędzy 0,6s i 1s od startu arduino. Możesz na próbę odłączyć przełączniki i zobaczyć czy bez przewodów podpiętych pod piny dalej występuje. Ewentualnie rzucę jeszcze raz okiem na log z kolejnego uruchomienia, bo może INPUT_PULLUP coś wyjaśni.

Aby mieć taki dokladny debug, pamiętaj o odkomentowaniu (usunięcie ";" na początku) ";    -D DEBUG_STARTUP" w pliku "platformio.ini" - Zakomentowałem, bo inni mogą tego nie potrzebować.

**Comment by lkankowski** [comment]
I rzuć okiem na koniec pliku https://github.com/lkankowski/arduino-multi-relay2/blob/develop/README.md
Dodałem kilka poleceń. Opis na razie roboczy.

**Comment by pepeEL** [comment]
Ok jutro odłączę ale jak na stole wgrywałem to nie załącza przekaźników.

**Comment by pepeEL** [comment]
I gdzie używać tych poleceń co piszesz?

**Comment by pepsonEL** [comment]
Wgrałem i powiem Ci tak. To jest jakiś cyrk 👍 Teraz jak wgrałem program na Arduino Mega od ośw. parteru z właczonym debugowaniem i wartościa 23 wymuszenia czyszczenia eeprom to teraz przy restartach na dolnym arduino nie zapalaja sie juz światła. Poniżej logi:
https://pastebin.com/myU7zdLz

Natomiast jak wgrałem na arduino od piętra z i wartośc dałem chyba 26 czyszczenie eeprom to teraz na piętrze zapala się naprzemian oświetlenie na holu gdzie nie ma fizycznego przycisku. Nie jest nawet przewód podłaczony. I teraz pierwszy start np oświetlenie hol zapala się, klikam restart arduino mega to startuje i oświetlenie gaśnie. Kolejny restart znów zapal, kolejny gaśnie i tak na zmiane tylko to jedno oświetlenie.
Poniżej logi
https://pastebin.com/wmyB3N3z



Ja nie wiem czy to nie jest coś z czyszczeniem eeprom. Nie wiem już....

**Comment by pepsonEL** [comment]
Pożniej jeszcze wgrałem raz na Arduino od parteru tylko wyłaczyłem debugowanie to zaawansowane. I losowe zapalanie wróciło. Jak ponownie wgrałem z debugowaniem to ok znów na parterowym się już nie zapalały. Jednak na tym od piętra nic nie pomagało....
I sprawa też taka jak zostawiłem to na parterowym wgrane , a w HA mam zrobiony skrypt że jak go uruchamiam to gasi mi wszystkie w domu światła to nie chciały się gaziś na parterze.... Gasło jedno dwa... czyli musiałem kilka razy skrypt uruchomić.... 
Na starej wersji działa poprawnie że gasną wszystkie..... 
Nie wiem może gdzieś trzeba jakieś zwłoki dać.... może coś za szybko się uruchamia i coś się testuje i wtedy zapala je... nie wiem a jak debugowanie jest właczone może coś dłużej sie uruchamia nie wiem juz co jest grane.

**Comment by lkankowski** [comment]
Wg mnie masz ewidentnie coś z hardwarem.
Sam fakt, że napisałeś, że na biurku działa oznacza tyle, że to kwestia poza oprogramowaniem.
Dodatkowo napisałeś, że masz włączniki mechaniczne lub pin jest niepodłączony. Tymczasem wg tego zapisu loga:
```
# 53 Debug startup - buttons pin state
# 54 1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
```
Stan drugiego włącznika (Ośw. hol piętro), czyli pinu 55 jest LOW, a w 934ms od startu wraca do stanu spoczynkowego, czyli HIGH:
```
Ośw. hol piętro - Click for relay 1
# 79:934 Relay::changeState: old_state=1, new_state=0, _hasStartupOverride=0, _eepromIndex=1, (uint8_t) state=0, _isImpulse=0
```
To może sugerować jakieś błędy w okablowaniu, błędy w połączeniu GND.
Podczas kolejnego startu, pinu obu pierwszych włączników mają stan LOW.

Zwracam też uwagę, że czyszczenie eeprom następuje tylko przy pierwszym starcie po podbiciu nr CONFIG_VERSION.

Poza tym masz błąd w konfiguracji włączników, choć to raczej nie ma znaczenie w kontekście załączania przekaźników na starcie:
```
# 29 > -1;0;2;-1;-1;Ośw. podbitka l.choinkowe
```
Obecnie nie ma już potrzeby definiowania wirtualnych przełączników.

Podsumowując:
1. dokładnie sprawdź okablowanie, wymień arduino na inne, sprawdzaj "na stole" - może potrzebujesz weryfikacji fachowca?
2. w realnym życiu restart występuje bardzo rzadko, więc problem jest marginalny (o ile faktycznie dotyczy oprogramowania)
3. wnioski odnośnie obserwacji opóźnień i innego zachowania instalacji mogą być mylne. Obecna wersja jest 50% szybsza niż poprzednia, więc możliwe, że ujawnia problemy, które zawsze występowały. Zakładam, że jeszcze nie mieszkasz, bo skupiasz się na kwestii startu. Ja swego czasu miałem problemy z hardware - wadliwy włącznik powodował włączanie światła w sypialni w środku nocy. Doprowadziło to do sporej frustracji mojej żony względem tych naszych automatyzmów, więc radzę porządnie podejść do kwestii jakości połączeń elektrycznych i kabli.
4. Zebrane z logów materiały raczej wskazują na problem hardware, więc to zgłoszenie kwalifikuje się do zamknięcia. Oczywiście, nie wykluczam błędu w oprogramowaniu, ale zebrane materiały temu przeczą, a dodatkowo ja korzystam z tego softu 24/7 i problemów nie ma.

**Comment by pepeEL** [comment]
Wiesz mnie mocno dziwi że jak debugowanie jest włączone to arduino od parteru teraz zaczęło działać poprawnie. A jak debugowanie wyłączę to problem znów wraca.
A na arduino od piętra mimo włączonego czy wyłączonego problem jest. I jak widzisz zapala światło na holu gdzie przewód od tego światła jest nie podłączony i nie ma przycisku. 
A jak zasilasz arduino? Z usb w raspberry? Czy jak?

**Comment by pepsonEL** [comment]
I odnośnie tego błedu wirtualnego włacznika.... to wywalić go poprostu z konfiguracji tak ? Jeśli chce aby on tylko był dostępny z HA a fizycznie nie ma do niego włacznika ?

**Comment by lkankowski** [comment]
Zasilam z dedykowanego zasilacza 5V.
Na wszystkie pozostałe pytania już odpowiedziałem - przeczytaj uważnie poprzednie posty.

**Comment by pepeEL** [comment]
Jutro podmienię arduino i zobaczę. Jak nie to wracam do 1.2

**Comment by pepsonEL** [comment]
Z przykrością musze powiedzieć że niestety muszę pozostać na wersji 1.2 bo ona działa poprawnie. Natomiast na nowej wersji 2.0 jest wciąż problem. Jeśli na jednym arduino właczyłem debugowanie to zaczęło działać ale na innym nadal jest problem. Zmieniłem już sprzętowo arduino ale to nic nie dało(zupełnie nowe dopiero odpakowane). Jak wyłącze debugowanie problem znów wraca na tym jednym arduino. Poprawiłem już masy wszystkich przewodów. Dziwne że na starym sofcie 1.2 działa poprawnie. Jak odłaczyłem od Arduino przewody przycisków to problem znika. Mam przyciski Legrand Niloe i idzie do nich skrętka. Kazdy przycisk ma dla siebie osobną żyłę w skrętce jako MASA. Nie wiem co jeszcze może być problemem. Jak dla mn\ie to coś w napisaniu softu jest... skoro stara wersja działa, jak włacztyłem na jednym arduino debugowanie też nagle po ostatnich poprawkach softu zaczęło działać.... a jak wyłacze debugowanie to problem wraca. Szzkoda bo wersja 2.0 jak dla mnie jest super. No ale u mnie nie chce ona poprawnie działać. Nie mam już pojęcia czemu.

**Comment by lkankowski** [comment]
Ależ ja nie czuję żadnej przykrości :)
Twoja sprawa czego używasz w domu.

Niemniej już Ci pokazałem na logach, że z Twoją instalacją pod względem połączeń elektrycznych jest coś nie tak. Jak Ci chata zacznie mrugać, to Ci żona wyrzuci całość i zamówi fachowca :D

W ostatnim wpisie aż dwukrotnie udowadniasz, że to problem instalacji :)
1. "Jak odłaczyłem od Arduino przewody przycisków to problem znika" - i to by się zgadzało, bo logi jasno pokazują inicjowanie zmiany stanu przez pin przełącznika
2. "Zmieniłem już sprzętowo arduino ale to nic nie dało" - czyli jedyny wspólny mianownik, to instalacja

Zatem niebawem spokojnie mogę zamknąć to zgłoszenie, a jak pojawią się twarde dowody na błąd w oprogramowaniu, to najwyżej otworzymy.

**Comment by pepsonEL** [comment]
Dziwne tylko że w jednym arduino zapalało światło gdzie nie było przycisku....

**Comment by pepsonEL** [comment]
Zasilanie arduino mam z usb odroida. Kurczę naprawdę nie wiem co jest grane....

**Comment by lkankowski** [comment]
Ja mam osobny zasilacz 5V/10A i zasilam z niego Raspberry PI 3B+, Arduino Mega (bezpośrednio na pin +5V) i wszystkie moduły przekaźników. Zasilacz jest z dużym zapasem, ale planuję dokładać kolejne odbiorniki.

**Comment by pepsonEL** [comment]
A na które piny w MEGA dajesz 5V ?

**Comment by pepsonEL** [comment]
A raspberry dajesz zasilanie pod wtyk microUSB czy pod piny 5V i GDN na goldpuinach ?

**Comment by lkankowski** [comment]
Raspberry zasilam przez micro usb

**Comment by pepsonEL** [comment]
Ale też z tego zasilacza.... Kurcze tak szukam szukam i szukam co może być przyczyną.... Jeszcze wgram soft z grupy od usera EasySwitch. On też zaczął soft robić z long i dual click... i na jego sofcie działało też bez problemu. Tyle że nie skończył tego softu.... i miał kilka wad... Jutro wgram go jeszcze raz....

**Comment by pepsonEL** [comment]
WItam. Wykonałem kolejne testy. Wgrałem sketch zrobiony za pomocą softu usera z grupy EasySwitch.pl Tym softem:
https://sklep.easyswitch.pl/produkt/easyswitch_easysensors/

Zrobiłem indentyczną konfigurację jak na Twoim sofcie , dałem nawet więcej z dwuklikiem i długim klikiem. I nic nie dzieje się. Nic nie wariuje. Na innych co prawda zwykłych softach czyli tylko on/off też działa wszystko ok. Tylko na tym Twoim jest problem gdzie zaimplementowałeś dwuklik i long klik. Uważam że coś jest źle napisane skoro inne nie mają takiego problemu. Używałem Twojego softu 1.2 i używam i naprawdę on działa super.I chciałbym użyć tego w wersji 2.0 ale mając taki efekt nie mogę. 
Natomiast soft EasySwitch ma jeszcze kilka wad i dlatego też nie mogę go używać.... A user chwilowo zaprzestał działań...

A to moj konfig z softu easyswicth
https://pastebin.com/7zxRyiTV

**Comment by lkankowski** [comment]
A spróbuj taki sketch:
```
#include <Arduino.h>

void setup() {
    Serial.begin(115200);
    pinMode(JAKIŚ_PIN1, INPUT_PULLUP);
    pinMode(JAKIŚ_PIN2, INPUT_PULLUP);
    pinMode(JAKIŚ_PIN3, INPUT_PULLUP);
};

void loop() {
    Serial.println(string(millis())+"; Stan pinu: "+JAKIŚ_PIN1+"="+digitalRead(JAKIŚ_PIN1));
    Serial.println(string(millis())+"; Stan pinu: "+JAKIŚ_PIN2+"="+digitalRead(JAKIŚ_PIN2));
    Serial.println(string(millis())+"; Stan pinu: "+JAKIŚ_PIN3+"="+digitalRead(JAKIŚ_PIN3));
    delay(50);
}
```
W miejsce JAKIŚ_PINx wpisz piny przełączników, które sprawiają problem. Możesz odpalić na obu instalacjach domowych po kilka razy i obserwuj wyniki.
Jak chcesz wkleić na pastebin, to koniecznie opisz w pliku, jakiego urządzenia dotyczy log.

**Comment by pepsonEL** [comment]
https://pastebin.com/6rUddR4Z

Nie chce mi się skompilować... Pewnie coś źle wpisałem....

**Comment by lkankowski** [comment]
"String" z dużej litery - pomyliłem się :)

**Comment by pepsonEL** [comment]
OK wgrałem. Podłaczyłem do Arduino z oświetleniem parteru gdzie są klawisze na pinach co post wyżej podałe: A6, A7, A8, A10, 46, 50, 51 i jak podłączyłem z laptopem to to otrzymywałem na serial monitorze takie coś. Oczywiście to sprawdzam w domu tam gdzie był problem:
https://pastebin.com/TeKeXpK6

**Comment by lkankowski** [comment]
No ciekawe.
Stanu ponad 2000ms nie musisz wklejać, no chyba że pojawi się wartość "0".
Poodpalaj kilka razy i koniecznie na instalacji gdzie występował problem bez żadnej ingerencji w układ, na którym występuje problem (bez odłączenia pinów, kabli, itp.) - tylko wgranie innego sketcha.

Jeżeli się potwierdzi, że nie występuje stan "0", to wrócę do weryfikacji problemu.

**Comment by pepsonEL** [comment]
OKi zaraz zrobię ci kolejne testy. Tak robie to na instalacji gdzie jest problem. Jedyne wgrywam ten sketch na drugie arduino i wpinam to drugie na piny(zeby nie flashowac za kazdym razem tylko zmieniam samo arduino). No i mam podlaczone pod USB do komputera. Zrobię też test na arduino PIĘTRA gdzie był jak pamietam jeden pin problematyczny gdzie nie było klawisz nawet podłaczonego.

**Comment by pepsonEL** [comment]
logi z podłaczenia do instalacji na parterze. Kila razy restartowałem Arduino. Ponizej logi
https://pastebin.com/Ehuur23F

**Comment by pepsonEL** [comment]
A to logi z instalacji pietra gdzie problemem bnył niby przycisk na pinie A1 a fizycznie nawet nie był przycisk tam podłączony ani kabel idący do niego....
https://pastebin.com/Su2ZBzff

**Comment by lkankowski** [comment]
No ciekawa sprawa, że tu nigdzie nie ma stanu LOW, choć jak to w software, nie jest rozstrzygające. Jest wiele czynników.

Odpal proszę aktualną wersję kodu ponownie tam, gdzie występuje problem.
Tym razem poza "DEBUG_STARTUP" odkomentuj jeszcze "-D IGNORE_BUTTONS_START_MS=2000" - możliwe, że to zamaskuje problem.
Dokładnie mi opisz, jakie są efekty przed każdym odpaleniem w treści loga.
Zrestartuj też kilka razy, ale pamiętaj, że jeżeli przy pierwszym odpaleniu światło się zaświeci i zrobisz reset, to normalne, że zaświeci się ponownie - to nie jest błąd.
Natomiast jeżeli wgrywasz nową wersję z podbitym CONFIG_VERSION, to zaraz po wgraniu Arduino zdąży się odpalić i to z reguły zanim zdążysz włączyć serial monitor. Podłączenie serial monitora restartuje Arduino i jest to już kolejne uruchomienie.
Poza tym fajnie by było, gdybyś na instalacji zasilał z normalnego zasilacza, a nie USB.

**Comment by pepsonEL** [comment]
Powiem tak. Wgrałem teraz tak jak napisałeś i teraz jest wszystko ok. Żadne światło nie zapaliło się na parterze ani na piętrze. 
Zakomentowałem też DEBUG_STARTUP zostawiając tylko odkomentowane "-D IGNORE_BUTTONS_START_MS=2000" i też nie zapaliło się.
Teraz jak dla mnie jest ok pytanie czy coś będziesz teraz poprawiał w kodzie czy już nie ?

**Comment by lkankowski** [comment]
To tylko programowe zamaskowanie problemu ;)
Podeślij logi z kilku uruchomień, a na początek zrób czyszczenie eeprom.

**Comment by pepsonEL** [comment]
Pietro logi zaprogramowane i od razu serial monitor. Programowałem jak arduino jest wpiete w rozdzielni wiec serial monitor od razu pokazał logi od pierwszego odpalenia i potem ok 5 restartów....
https://pastebin.com/MeYCefVS


A tu tak samo ale parterowe logi
https://pastebin.com/trXrYQnN

**Comment by lkankowski** [comment]
Ciekawa sprawa, bo wg logów nawet bez "IGNORE_BUTTONS_START_MS=2000" by zadziałało :D

**Comment by pepsonEL** [comment]
Hmmm to ja już nie wiem.... A nic nie zrobiłem. Zawsze tak samo wgrywałem... Chyba że coś w ostatniej wersji zmieniłeś i to spowodowało że działa... Ja wgrywam najpierw sketch czyszczący eeprom przez Arduino IDE taki:
https://pastebin.com/TSbSSXg5

A potem wgrywam Twój najnowszy program z podbitą wersją CONFIG_VERSION.... i zawsze tak samo robiłem. A nic nie zmieniłem też w instalacji... więc nie wiem co jest grane....

**Comment by lkankowski** [comment]
Ważne, że śmiga.

**Comment by pepsonEL** [comment]
Czyli co zakomentować debugowanie i zakomentować też "IGNORE_BUTTONS_START_MS=2000" ?

**Comment by pepsonEL** [comment]
Jednak pospieszyłem się... Coś jednak musiało być nie tak albo wgrane. Bo dziś wgrałem oba sketche na piętro i parter z zakomentowanym debugowaniem na starcie i zakomentowane "IGNORE_BUTTONS_START_MS=2000" i niestety taki sam efekt jak na początku. Zapalają się światła. 
Jak odkomentowałem "IGNORE_BUTTONS_START_MS=2000" to jest DOBRZE ale tylko wtedy.... Myślę że trzeba otworzyć dalej wątek i szukać rozwiązania :)

**Comment by lkankowski** [comment]
skoro działa z "IGNORE_BUTTONS_START_MS=2000", to z tego korzystaj. Po prostu, przez pierwsze 2s wszelkie zmiany stanów przełączników są ignorowane :)

**Comment by pepsonEL** [comment]
Aha. no ok. Może kiedyś wynajdzie sie problem.
