### ISSUE TITLE
Zrywanie komunikacji po eth arduino mega i w5500

### ISSUE THREAD

**Issue by paku2020** [lkankowski/arduino-multi-relay2#40]
Witam,

Mam dziwny problem z moją instalacją.
Sprawa wygląda tak, że mam płytkę od easyswitch, a na niej arduino mega i w5500 - ES-1.04.
Wgrałem arduino-multi-relay2 i ogólnie działa.
Połączenie ethernet też działa, z tym właśnie że co jakiś czas połączenie się wiesza. Program sam w sobie działa, klawisze działają, przekaźniki też ale nie ma komunikacji po ethernet. Port nie faluje, cały czas 100mb. Zasilanie raczej też stabilne z zasilacza buforowego. Wymiana zasilacza na inny też nie pomogła.
Wcześniej pod ten kabelek było podłączone rpi i nigdy nie było problemu. Więc raczej kabel jest ok.
Te piny w arduino mam wolne
0,1,4,5,7,9,10,13,14,15,16,21,22,50,51,52,53.

Co jeszcze mogę sprawdzić aby znaleźć przyczynę problemu? Jakiś debug lub coś?
W innej lokalizacji mam arduino mega z w5100 i nie ma żadnego problemu. 
Wgramy ten sam sketch.

**Comment by lkankowski** [comment]
Nie mam pojęcia jak Ci pomóc, bo cała komunikacja siedzi w MySensors - może jest tam jakaś funkcja "watchdog", która potrafi wykryć rozłączanie i zainicjować na nowo?
Inny trop jaki mogę zasugerować, to poszukanie innej biblioteki lub innej wersji do obsługi w5500 wspieranej przez MySensors.

**Comment by paku2020** [comment]
Sam nie mam pomysłu. Różne próby robiłem. Problem też jest taki że nie mam za bardzo doświadczenia z pisaniem kodów pod to.
No nic to zamykam ten temat :)
Pozdrawiam
