### ISSUE TITLE
Mcp23017 15+ pins problem

### ISSUE THREAD

**Issue by kamyrdol32** [lkankowski/arduino-multi-relay2#42]
Hello, i have problem with Mcp23017 Expander. E(0, 1) - E(0, 15) worka fine but when i want to add more than 15 program dont work (without error, i dont have output on startup ). 

`{22, E(0, 22), RELAY_TRIGGER_HIGH, -1, "RELAY 22"}, `

PL
Witam, mam problem z ekspanderem Mcp23017. Przy próbie dodania wyjść na porcie 15+ program wgrywa się poprawnie lecz nie działa, nie otrzymuje nawet informacji zwrotnej dotyczącej statusów itp

**Comment by lkankowski** [comment]
MCP23017 has only 16 pins, so only 0-15 are allowed.

**Comment by kamyrdol32** [comment]
Problem solved. I have 128 pin extension and i used E(0, 2) and E(1, 2)

**Comment by lkankowski** [comment]
Exactly :)
Probably you have 8 MCP23017 on board, so you have to address every single one using `E` macro like:
```
E(x, y)
```
where:
- `x` is MCP... id (0-7)
- `y` is pin number
