### ISSUE TITLE
DEBUG_STARTUP flag hangs Arduino nano

### ISSUE THREAD

**Issue by chytreg** [lkankowski/arduino-multi-relay2#8]
I've tried to use all `DEBUG_` options and when I enable `DEBUG_STARTUP` flag I think the controller hangs at some point, it does not print anything to the serial console.

**Comment by chytreg** [comment]
@LeszekKankowski I'm closing this once because the root cause of the problem is the lack of SRAM on Arduino Nano.
Nano has only 2KB of SRAM :( Anyway, I've tried to make some optimization, maybe later will share the code after cleanup, but still, it will be very hard to run it properly on Arduino nano, in general, I succeeded it's doable but limited to the amount of Relay/Buttons.

**Comment by lkankowski** [comment]
Well - maybe get rid of MySensors libraries will help - there is very simple subset of MySensors protocol used. It can be done with pretty simple serial output.
Unfortunately, I haven't done the abstraction above MySensors :(
