### ISSUE TITLE
Nie można skompilować sketcha

### ISSUE THREAD

**Issue by pepsonEL** [lkankowski/arduino-multi-relay2#9]
WItam.
Mam arduino i dokupiłem do niego eksapnder skladający się z 4 kości MC23017. Zrobiłem konfig.... który wygląda tak:
// for development purposes copy "config.h.sample" into "config.h" file or use link:
// - Windows 10 (PowerShell) as admin: Start-Process -FilePath "$env:comspec" -ArgumentList "/k", "mklink", "config.h","config.h.sample" -Verb RunAs
// For production you can customize "config.h" or use link to "config.h.local":
// - Start-Process -FilePath "$env:comspec" -ArgumentList "/k", "mklink", "config.h","config.h.local" -Verb RunAs
// Alternative version:
// Start-Process -Verb RunAs -FilePath "powershell" -ArgumentList "-NoExit","-command","New-Item -Path '$(Get-Location)\include\config.h' -ItemType SymbolicLink -Value '$(Get-Location)\include\config.h.sample'"

// For mono-stable buttons it will trigger state: LOW - when button is pressed, HIGH - when button is released
const uint8_t MONO_STABLE_TRIGGER = LOW;

// time interval for RELAY_IMPULSE type relay, ignored when button type is DING_DONG or REED_SWITCH
const unsigned long RELAY_IMPULSE_INTERVAL = 250;

// debounce interval in milliseconds
const unsigned long BUTTON_DEBOUNCE_INTERVAL = 50;

// double-click interval in milliseconds
const unsigned long BUTTON_DOUBLE_CLICK_INTERVAL = 350;

// long-press interval in milliseconds
const unsigned long BUTTON_LONG_PRESS_INTERVAL = 800;

#ifdef USE_EXPANDER
  uint8_t expanderAddresses[] = {0, 1, 2, 3}; //MCP23017
#endif

const char MULTI_RELAY_DESCRIPTION[] = "Multi Relay";

// Relays config - ID and PIN MUST BE UNIQUE (can't be repeated)!
// Row params: relay ID - [0-254] sensor ID reported on MySensor Gateway
//             relay pin - pin used for relay, can be expander pin via "E(x, y)" macro
//             relay options - [RELAY_TRIGGER_LOW|RELAY_TRIGGER_HIGH] {RELAY_STARTUP_ON|RELAY_STARTUP_OFF} {RELAY_IMPULSE}
//             relay description - reported on MySensor Gateway, can help identify device on initial configuration in Home Automation App, can be empty ("")
const RelayConfigDef gRelayConfig[] = {
  {0, 12, RELAY_TRIGGER_HIGH, "Ośw. hol-1 sekcja"},  // WŁ: przy wej. z wiatrołapu (podwójny), przy wejściu do salonu (podówjny), doł przy schodach (podwójny)
  {1, 11, RELAY_TRIGGER_HIGH, "Ośw. zew. od ogrodu"},  // WŁ: wiatrołap przy wejściu do domu (podwójny)
  {2, 10, RELAY_TRIGGER_HIGH, "Ośw. nad tarasem"},  // WŁ: przy wyjściu na taras (podwójny)
  {3, 9, RELAY_TRIGGER_HIGH, "Ośw. na tarasie"},  // WŁ: przy wyjściu na taras (podwójny)
  {4, 8, RELAY_TRIGGER_HIGH, "Ośw. klatka-schody"},  // WŁ: klatka przy schodach dół i góra
  {5, 7, RELAY_TRIGGER_HIGH, "Ośw. klatka-kinkiety"},  // WŁ: klatka przy schodach dół i góra
  {6, 6, RELAY_TRIGGER_HIGH, "Ośw. kotłownia"},  // WŁ: przy wejściu z garażu + wyjście z kotłowni na zewnątrz=mostek z garażem
  {7, 5, RELAY_TRIGGER_HIGH, "Ośw. garaż-1 sekcja"},  // WŁ: przy wejściu do garażu (podwójny), wejście do kotłowni (podwójny)
  {8, 4, RELAY_TRIGGER_HIGH, "Ośw. garaż-2 sekcja"},  // WŁ: przy wejściu do garażu (podwójny), wejście do kotłowni (podwójny)
  {9, 3, RELAY_TRIGGER_HIGH, "Ośw. przed wejściem"},   // WŁ: wiatrołap przy wejściu do domu (podwójny)
  {10, 2, RELAY_TRIGGER_HIGH, "Ośw. zew. od kotłowni"},  // WŁ: wiatrołap przy wejściu do domu (podwójny)
  {11, 14, RELAY_TRIGGER_HIGH, "Ośw. zew. przed garażem"},  // WŁ: wiatrołap przy wejściu do domu (podwójny)
  {12, 15, RELAY_TRIGGER_HIGH, "Ośw. wiatrołap"},  // WŁ: wiatrołap przy wejściu do domu i wejściu z wiatrołapu do holu
  {13, 16, RELAY_TRIGGER_HIGH, "Ośw. salon kinkiety"},  // WŁ: wejście do salonu (podwójny), przy wykuszu
  {14, 17, RELAY_TRIGGER_HIGH, "Ośw. salon sufit"},  // WŁ: wejście do salonu (podwójny), przy wykuszu
  {15, 18, RELAY_TRIGGER_HIGH, "Ośw. łazienka parter-kinkiet"},  // WŁ: wejście do łazienki+lustro=zmostkowan
  {16, 19, RELAY_TRIGGER_HIGH, "Ośw. łazienka parter-sufit"},  // WŁ: wejście do łazienki+lustro=zmostkowan
  {17, 22, RELAY_TRIGGER_HIGH, "Ośw. salon nad stołem"},  // WŁ: wejście do salonu, przy wykuszu
  {18, 23, RELAY_TRIGGER_HIGH, "Ośw. gabinet-sufit1"},  // WŁ: wejście do gabinetu (podwójny)
  {19, 24, RELAY_TRIGGER_HIGH, "Ośw. gabinet-kinkiet"},  // WŁ: wejście do gabinetu
  {20, 25, RELAY_TRIGGER_HIGH, "Ośw. kuchnia-1 sekcja"},  // WŁ: kuchnia z prawej strony lodówki (podwójny),wejście do salonu (podwójny)
  {21, 26, RELAY_TRIGGER_HIGH, "Ośw. kuchnia-2 sekcja"},  // WŁ: kuchnia z prawej strony lodówki (podwójny),wejście do salonu (podwójny)
  {22, 27, RELAY_TRIGGER_HIGH, "Ośw. kuchnia-LEDY"},  // WŁ: wejście do salonu
  {23, 28, RELAY_TRIGGER_HIGH, "Ośw. schowek"},  // WŁ: schowek
  {24, 29, RELAY_TRIGGER_HIGH | RELAY_IMPULSE, "Brama garażowa"},  // WŁ: wej do garażu
  {25, 30, RELAY_TRIGGER_HIGH | RELAY_IMPULSE, "Brama wjazdowa"},  // WŁ: wej do garażu
  {26, 31, RELAY_TRIGGER_HIGH, "Kontaktron brama"},  // kontaktron na bramie wjazdowej
  {27, 32, RELAY_TRIGGER_HIGH, "WLED salon"},  // wirtualny przekaźnik dla sterowania modułem WLED-salon
  {28, E(2,0), RELAY_TRIGGER_HIGH, "Ośw. zew. balkon"},  // WŁ: przy balkonie Zuzia i Pokój2 (podwójny)
  {29, E(2,1), RELAY_TRIGGER_HIGH, "Ośw. hol piętro"},  // WŁ: przy schodach, przy domofonie piętro, przy garderobie hol
  {30, E(2,2), RELAY_TRIGGER_HIGH, "Ośw. podbitka l.choinkowe"},  // WŁ: BRAK
  {31, E(2,3), RELAY_TRIGGER_HIGH, "Ośw. pokój2-sufit"},  // WŁ: przy wejściu
  {32, E(2,4), RELAY_TRIGGER_HIGH, "Ośw. pokój2-kinkiety"},  // WŁ: przy wejściu, przy balkonie (podwójny)
  {33, E(2,5), RELAY_TRIGGER_HIGH, "Ośw. Zuzia-sufit"},  // WŁ: przy wejściu
  {34, E(2,6), RELAY_TRIGGER_HIGH, "Ośw. Zuzia-kinkiety"},  // WŁ: przy wejściu, przy balkonie (podwójny)
  {35, E(2,7), RELAY_TRIGGER_HIGH, "Ośw. łazienka piętro-sufit1"},  // WŁ: wej. do łazienki (podwójny)
  {36, E(2,8), RELAY_TRIGGER_HIGH, "Ośw. łazienka piętro-LEDY"},  // WŁ: wej. do łazienki (podwójny)
  {37, E(2,9), RELAY_TRIGGER_HIGH, "Ośw. łazienka piętro-kinkiet1"},  // WŁ: przy lustrze po prawo i lewo
  {38, E(2,10), RELAY_TRIGGER_HIGH, "Ośw. pralnia"},  // WŁ: przy wej. do pralni
  {39, E(2,11), RELAY_TRIGGER_HIGH, "Ośw. strych"},  // WŁ: przy wej. do pralni
  {40, E(2,12), RELAY_TRIGGER_HIGH, "Ośw. garderoba hol"},  // WŁ: na holu przy wejściu do garderoby
  {41, E(2,13), RELAY_TRIGGER_HIGH, "Ośw. sypialnia-1 tuba"},  // WŁ: przy wej do sypialni (podwójny)
  {42, E(2,14), RELAY_TRIGGER_HIGH, "Ośw. sypialnia-2 tuby"},  // WŁ: przy wej do sypialni (podwójny)
  {43, E(2,15), RELAY_TRIGGER_HIGH, "Ośw. garderoba sypialnia"},  // WŁ: przy wej. do garderoby w sypialni
  {44, E(3,0), RELAY_TRIGGER_HIGH, "Ośw. sypial.-kin.Piotr"},  // WŁ: przy łóżku PIOTREK
  {45, E(3,1), RELAY_TRIGGER_HIGH, "Ośw. sypial.-kin.Iza"},  // WŁ: przy łóżku IZA
  {46, E(3,2), RELAY_TRIGGER_HIGH, "Ośw. hol-2 sekcja"},  // WŁ: przy wej. z wiatrołapu (podwójny), przy wejściu do salonu (podówjny), doł przy schodach (podwójny)
  {47, E(3,3), RELAY_TRIGGER_HIGH, "Ośw. gabinet-sufit2"},  // WŁ: wejście do gabinetu (podwójny)
  {48, E(3,4), RELAY_TRIGGER_HIGH, "Ośw. łazienka piętro-kinkiet2"},  // WŁ: przy lustrze po prawo i lewo
  {49, E(3,5), RELAY_TRIGGER_HIGH, "Ośw. łazienka piętro-sufit2"},  // WŁ: wej. do łazienki (podwójny)
  {50, E(3,6), RELAY_TRIGGER_HIGH, "WOLNY"},  //
  {51, E(3,7), RELAY_TRIGGER_HIGH, "WOLNY"}  //
};

// Buttons config
// Row params: button pin - pin used for button, can be expander pin (but NOT RECOMMENDED) via "E(x, y)" macro
//             button type - [MONO_STABLE|BI_STABLE|DING_DONG|REED_SWITCH]
//             click action relay ID - MUST be defined in gRelayConfig
//             long-press action relay ID - ignored for BI_STABLE, DING_DONG, REED_SWITCH
//             double-click action relay ID - ignored for DING_DONG, REED_SWITCH
//             button description - debug only, can be empty ("")
const ButtonConfigDef gButtonConfig[] = {
  {A0, MONO_STABLE, 0, -1, 29, "Ośw. hol-1 sekcja"},  // WŁ: przy wej. z wiatrołapu (podwójny), przy wejściu do salonu (podówjny), doł przy schodach (podwójny)
  {A1, MONO_STABLE, 1, -1, -1, "Ośw. zew. od ogrodu"},  // WŁ: wiatrołap przy wejściu do domu (podwójny)
  {A2, MONO_STABLE, 2, -1, -1, "Ośw. nad tarasem"},  // WŁ: przy wyjściu na taras (podwójny)
  {A3, MONO_STABLE, 3, -1, -1, "Ośw. na tarasie"},  // WŁ: przy wyjściu na taras (podwójny)
  {A4, MONO_STABLE, 4, -1, -1, "Ośw. klatka-schody"},  // WŁ: klatka przy schodach dół i góra
  {A5, MONO_STABLE, 5, -1, -1, "Ośw. klatka-kinkiety"},  // WŁ: klatka przy schodach dół i góra
  {A6, MONO_STABLE, 6, -1, -1, "Ośw. kotłownia"},  // WŁ: przy wejściu z garażu + wyjście z kotłowni na zewnątrz=mostek z garażem
  {A7, MONO_STABLE, 7, -1, -1, "Ośw. garaż-1 sekcja"},  // WŁ: przy wejściu do garażu (podwójny), wejście do kotłowni (podwójny)
  {A8, MONO_STABLE, 8, -1, -1, "Ośw. garaż-2 sekcja"},  // WŁ: przy wejściu do garażu (podwójny), wejście do kotłowni (podwójny)
  {A9, MONO_STABLE, 9, -1, -1, "Ośw. przed wejściem"},   // WŁ: wiatrołap przy wejściu do domu (podwójny)
  {A10, MONO_STABLE, 10, -1, -1, "Ośw. zew. od kotłowni"},  // WŁ: wiatrołap przy wejściu do domu (podwójny)
  {A11, MONO_STABLE, 11, -1, -1, "Ośw. zew. przed garażem"},  // WŁ: wiatrołap przy wejściu do domu (podwójny)
  {A12, MONO_STABLE, 12, -1, -1, "Ośw. wiatrołap"},  // WŁ: wiatrołap przy wejściu do domu i wejściu z wiatrołapu do holu
  {A13, MONO_STABLE, 13, -1, -1, "Ośw. salon kinkiety"},  // WŁ: wejście do salonu (podwójny), przy wykuszu
  {A14, MONO_STABLE, 14, -1, -1, "Ośw. salon sufit"},  // WŁ: wejście do salonu (podwójny), przy wykuszu
  {A15, MONO_STABLE, 15, -1, 16, "Ośw. łazienka parter-kinkiet"},  // WŁ: wejście do łazienki+lustro=zmostkowan
  {53, MONO_STABLE, 16, -1, 15, "Ośw. łazienka parter-sufit"},  // WŁ: wejście do łazienki+lustro=zmostkowan
  {52, MONO_STABLE, 17, 1, -1, "Ośw. salon nad stołem"},  // WŁ: wejście do salonu, przy wykuszu
  {51, MONO_STABLE, 18, -1, -1, "Ośw. gabinet-sufit1"},  // WŁ: wejście do gabinetu (podwójny)
  {50, MONO_STABLE, 19, -1, -1, "Ośw. gabinet-kinkiet"},  // WŁ: wejście do gabinetu
  {49, MONO_STABLE, 20, 22, 23, "Ośw. kuchnia-1 sekcja"},  // WŁ: kuchnia z prawej strony lodówki (podwójny),wejście do salonu (podwójny)
  {48, MONO_STABLE, 21, 22, 23, "Ośw. kuchnia-2 sekcja"},  // WŁ: kuchnia z prawej strony lodówki (podwójny),wejście do salonu (podwójny)
  {47, MONO_STABLE, 22, -1, -1, "Ośw. kuchnia-LEDY"},  // WŁ: wejście do salonu
  {46, MONO_STABLE, 23, -1, -1, "Ośw. schowek"},  // WŁ: schowek
  {45, MONO_STABLE, 24, -1, -1, "Brama garażowa"},  // WŁ: wej do garażu
  {44, MONO_STABLE, 25, -1, -1, "Brama wjazdowa"},  // WŁ: wej do garażu
  {43, REED_SWITCH, 26, -1, -1, "Kontaktron brama"},  // kontaktron na bramie wjazdowej
  {42, MONO_STABLE, 27, -1, -1, "WLED salon"},  // wirtualny przycisk dla sterowania modułem WLED-salon
  {E(0,0), MONO_STABLE, 28, -1, -1, "Ośw. zew. balkon"},  // WŁ: przy balkonie Zuzia i Pokój2 (podwójny)
  {E(0,1), MONO_STABLE, 29, -1, -1, "Ośw. hol piętro"},  // WŁ: przy schodach, przy domofonie piętro, przy garderobie hol
  {E(0,2), MONO_STABLE, 30, -1, -1, "Ośw. podbitka l.choinkowe"},  // WŁ: BRAK
  {E(0,3), MONO_STABLE, 31, -1, -1, "Ośw. pokój2-sufit"},  // WŁ: przy wejściu
  {E(0,4), MONO_STABLE, 32, -1, 31, "Ośw. pokój2-kinkiety"},  // WŁ: przy wejściu, przy balkonie (podwójny)
  {E(0,5), MONO_STABLE, 33, -1, -1, "Ośw. Zuzia-sufit"},  // WŁ: przy wejściu
  {E(0,6), MONO_STABLE, 34, -1, 33, "Ośw. Zuzia-kinkiety"},  // WŁ: przy wejściu, przy balkonie (podwójny)
  {E(0,7), MONO_STABLE, 35, 36, -1, "Ośw. łazienka piętro-sufit"},  // WŁ: wej. do łazienki (podwójny)
  {E(0,8), MONO_STABLE, 36, -1, -1, "Ośw. łazienka piętro-LEDY"},  // WŁ: wej. do łazienki (podwójny)
  {E(0,9), MONO_STABLE, 37, 36, 35, "Ośw. łazienka piętro-kinkiet1"},  // WŁ: przy lustrze po prawo i lewo
  {E(0,10), MONO_STABLE, 38, -1, 35, "Ośw. pralnia"},  // WŁ: przy wej. do pralni
  {E(0,11), MONO_STABLE, 39, -1, -1, "Ośw. strych"},  // WŁ: przy wej. do pralni
  {E(0,12), MONO_STABLE, 40, -1, -1, "Ośw. garderoba hol"},  // WŁ: na holu przy wejściu do garderoby
  {E(0,13), MONO_STABLE, 41, -1, 44, "Ośw. sypialnia-1 tuba"},  // WŁ: przy wej do sypialni (podwójny)
  {E(0,14), MONO_STABLE, 42, -1, 45, "Ośw. sypialnia-2 tuby"},  // WŁ: przy wej do sypialni (podwójny)
  {E(0,15), MONO_STABLE, 43, -1, -1, "Ośw. garderoba sypialnia"},  // WŁ: przy wej. do garderoby w sypialni
  {E(1,0), MONO_STABLE, 44, 41, 45, "Ośw. sypial.-kin.Piotr"},  // WŁ: przy łóżku PIOTREK
  {E(1,1), MONO_STABLE, 45, 41, 44, "Ośw. sypial.-kin.Iza"},  // WŁ: przy łóżku IZA
  {E(1,2), MONO_STABLE, 46, -1, 29, "Ośw. hol-2 sekcja"},  // WŁ: przy wej. z wiatrołapu (podwójny), przy wejściu do salonu (podówjny), doł przy schodach (podwójny)
  {E(1,3), MONO_STABLE, 47, -1, -1, "Ośw. gabinet-sufit2"},  // WŁ: wejście do gabinetu (podwójny)
  {E(1,4), MONO_STABLE, 48, 36, 35, "Ośw. łazienka piętro-kinkiet2"},  // WŁ: przy lustrze po prawo i lewo
  {E(1,5), MONO_STABLE, 49, 36, -1, "Ośw. łazienka piętro-sufit2"},  // WŁ: wej. do łazienki (podwójny)
  {E(1,6), MONO_STABLE, 50, -1, -1, "WOLNY"},  //
  {E(1,7), MONO_STABLE, 51, -1, -1, "WOLNY"}  //
};

Ale przy próbie kompilacji pojawia się taki błąd:

> Executing task: C:\Users\Piotrek\.platformio\penv\Scripts\pio.exe run <

Processing mega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/megaatmega2560.html
PLATFORM: Atmel AVR (2.2.0) > Arduino Mega or Mega 2560 ATmega2560 (Mega 2560)
HARDWARE: ATMEGA2560 16MHz, 8KB RAM, 248KB Flash
DEBUG: Current (simavr) On-board (simavr)
PACKAGES:
 - framework-arduino-avr 5.0.0
 - toolchain-atmelavr 1.50400.190710 (5.4.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 8 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Bounce2> 2.56.0
|-- <MySensors> 2.3.2
|   |-- <Wire> 1.0
|   |-- <SPI> 1.0
|   |-- <EEPROM> 2.0
|-- <Adafruit MCP23017 Arduino Library> 1.3.0
|   |-- <Wire> 1.0
|-- <EEPROM> 2.0
|-- <Wire> 1.0
Building in release mode
Compiling .pio\build\mega2560\src\Button.cpp.o
Compiling .pio\build\mega2560\src\Relay.cpp.o
src\Button.cpp: In member function 'void lkankowski::Button::attachPin(int)':
src\Button.cpp:45:43: error: no matching function for call to 'lkankowski::BounceExp::attach(int&, int)'
   _physicalButton.attach(pin, INPUT_PULLUP); // HIGH state when button is not pushed
                                           ^
In file included from src\Button.cpp:1:0:
include/Button.h:74:10: note: candidate: void lkankowski::BounceExp::attach(int)
     void attach(int pin) {
          ^
include/Button.h:74:10: note:   candidate expects 1 argument, 2 provided
Compiling .pio\build\mega2560\src\main.cpp.o
Compiling .pio\build\mega2560\lib558\Bounce2\Bounce2.cpp.o
*** [.pio\build\mega2560\src\Button.cpp.o] Error 1
================================================================================================== [FAILED] Took 2.90 seconds ==================================================================================================

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:02.898
============================================================================================= 1 failed, 0 succeeded in 00:00:02.898 =============================================================================================
The terminal process "C:\Users\Piotrek\.platformio\penv\Scripts\pio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

Proszę o pomoc.... bo w całym domu nie mam światła....

**Comment by lkankowski** [comment]
fixed
